# Generated by Django 4.2.4 on 2023-12-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_type', models.CharField(max_length=255)),
                ('product_url', models.URLField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
